export enum StatusEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    DISABLED = 'DISABLED',
    ENABLED = 'ENABLED',

    PENDING = 'PENDING',
    SUCCESS = 'SUCCESS',
    PROCESSING = 'PROCESSING',

    VALID = 'VALID',
    INVALID = 'INVALID',

    INTEGRITY = 'INTEGRITY',

    SECURITY = 'SECURITY',
    VALIDATION = 'VALIDATION',
    ACCOUNT = 'ACCOUNT',
    PACKAGE = 'PACKAGE'
}
